apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-echo
spec:
  selector:
    matchLabels:
      app: test-echo
  replicas: 2
  template:
    metadata:
      labels:
        app: test-echo
    spec:
      containers:
      - name: test-echo
        image: rms1000watt/dummy-golang-project
---
apiVersion: v1
kind: Service
metadata:
  name: test-echo
spec:
  type: LoadBalancer
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
  selector:
    app: test-echo
